In [3]:
!pip install requests

Requirement already satisfied: requests in c:\users\carol\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\carol\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\carol\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\carol\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\carol\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2023.11.17)

In [4]:
import requests

In [5]:
import requests

url = "https://api.themoviedb.org/3/authentication"

headers = {
    "accept": "application/json",
    "Authorization": " BEARER "
}

response = requests.get(url, headers=headers)

print(response.text)

{"success":true,"status_code":1,"status_message":"Success."}

In [6]:
import requests

url = "https://api.themoviedb.org/3/genre/movie/list?language=en"

headers = {
    "accept": "application/json",
    "Authorization": ""
}

response = requests.get(url, headers=headers)

print(response.json())

{'genres': [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 80, 'name': 'Crime'}, {'id': 99, 'name': 'Documentary'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}, {'id': 14, 'name': 'Fantasy'}, {'id': 36, 'name': 'History'}, {'id': 27, 'name': 'Horror'}, {'id': 10402, 'name': 'Music'}, {'id': 9648, 'name': 'Mystery'}, {'id': 10749, 'name': 'Romance'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 10770, 'name': 'TV Movie'}, {'id': 53, 'name': 'Thriller'}, {'id': 10752, 'name': 'War'}, {'id': 37, 'name': 'Western'}]}

In [7]:
import requests

url = "https://api.themoviedb.org/3/movie/popular?language=en-US&page=1&region=ES"

headers = {
    "accept": "application/json",
    "Authorization": ""
}

response = requests.get(url, headers=headers)

print(response.json())

{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/4woSOUD0equAYzvwhWBHIJDCM88.jpg', 'genre_ids': [28, 27, 53], 'id': 1096197, 'original_language': 'en', 'original_title': 'No Way Up', 'overview': "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.", 'popularity': 1532.906, 'poster_path': '/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg', 'release_date': '2024-01-18', 'title': 'No Way Up', 'video': False, 'vote_average': 6.479, 'vote_count': 499}, {'adult': False, 'backdrop_path': '/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg', 'genre_ids': [28, 878, 12], 'id': 823464, 'original_language': 'en', 'original_title': 'Godzilla x Kong: The New Empire', 'overview': 'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.', 'popularity': 1611.66, 'poster_path': '/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg', 'release_date': '2024-03-27', 'title': 'Godzilla x Kong: The New Empire', 'video': False, 'vote_average': 6.633, 'vote_count': 811}, {'adult': False, 'backdrop_path': '/FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg', 'genre_ids': [878, 28, 18], 'id': 934632, 'original_language': 'en', 'original_title': 'Rebel Moon - Part Two: The Scargiver', 'overview': 'The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.', 'popularity': 1523.65, 'poster_path': '/cxevDYdeFkiixRShbObdwAHBZry.jpg', 'release_date': '2024-04-19', 'title': 'Rebel Moon - Part Two: The Scargiver', 'video': False, 'vote_average': 6.149, 'vote_count': 575}, {'adult': False, 'backdrop_path': '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg', 'genre_ids': [878, 12], 'id': 693134, 'original_language': 'en', 'original_title': 'Dune: Part Two', 'overview': 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.', 'popularity': 1488.917, 'poster_path': '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', 'release_date': '2024-03-01', 'title': 'Dune: Part Two', 'video': False, 'vote_average': 8.259, 'vote_count': 3474}, {'adult': False, 'backdrop_path': '/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg', 'genre_ids': [16, 28, 10751, 35, 14], 'id': 1011985, 'original_language': 'en', 'original_title': 'Kung Fu Panda 4', 'overview': 'Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.', 'popularity': 1347.411, 'poster_path': '/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg', 'release_date': '2024-03-08', 'title': 'Kung Fu Panda 4', 'video': False, 'vote_average': 7.158, 'vote_count': 1405}, {'adult': False, 'backdrop_path': '/jnE1GA7cGEfv5DJBoU2t4bZHaP4.jpg', 'genre_ids': [28, 878], 'id': 1094844, 'original_language': 'en', 'original_title': 'Ape vs. Mecha Ape', 'overview': 'Recognizing the destructive power of its captive giant Ape, the military makes its own battle-ready A.I., Mecha Ape. But its first practical test goes horribly wrong, leaving the military no choice but to release the imprisoned giant ape to stop the colossal robot before it destroys downtown Chicago.', 'popularity': 1540.785, 'poster_path': '/dJaIw8OgACelojyV6YuVsOhtTLO.jpg', 'release_date': '2023-03-24', 'title': 'Ape vs. Mecha Ape', 'video': False, 'vote_average': 5.625, 'vote_count': 20}, {'adult': False, 'backdrop_path': '/5Eip60UDiPLASyKjmHPMruggTc4.jpg', 'genre_ids': [27, 9648, 53], 'id': 1041613, 'original_language': 'en', 'original_title': 'Immaculate', 'overview': 'An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.', 'popularity': 883.669, 'poster_path': '/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg', 'release_date': '2024-05-01', 'title': 'Immaculate', 'video': False, 'vote_average': 6.291, 'vote_count': 326}, {'adult': False, 'backdrop_path': '/ilK1JRbMjo4sMJtNKLOKnqRf1RH.jpg', 'genre_ids': [10752, 28, 36], 'id': 976906, 'original_language': 'en', 'original_title': 'Spitfire Over Berlin', 'overview': 'August 1944. With the American Eighth Air Force poised to strike over Nazi Germany, British Intelligence learns that they could be flying into a deadly trap. With only hours to spare, Flight Lieutenant Edward Barnes must fly a life and death mission over Berlin in his unarmed Spitfire to obtain photographic evidence and save the lives of 1200 men.', 'popularity': 815.831, 'poster_path': '/xtPPOPTad1qopK6uDe3VlYUa22o.jpg', 'release_date': '2022-05-13', 'title': 'Spitfire Over Berlin', 'video': False, 'vote_average': 3.615, 'vote_count': 13}, {'adult': False, 'backdrop_path': '/qnVm19Vu2Sc14LoEj82pmqAYr3p.jpg', 'genre_ids': [12, 28, 18], 'id': 845111, 'original_language': 'fr', 'original_title': 'Les trois mousquetaires : Milady', 'overview': "D'Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.", 'popularity': 842.014, 'poster_path': '/rtosxP5sXuoRFPH4sVbMccLIPiV.jpg', 'release_date': '2024-01-26', 'title': 'The Three Musketeers: Milady', 'video': False, 'vote_average': 6.553, 'vote_count': 356}, {'adult': False, 'backdrop_path': '/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg', 'genre_ids': [18, 12], 'id': 618588, 'original_language': 'en', 'original_title': 'Arthur the King', 'overview': 'Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.', 'popularity': 756.591, 'poster_path': '/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg', 'release_date': '2024-05-31', 'title': 'Arthur the King', 'video': False, 'vote_average': 6.7, 'vote_count': 76}, {'adult': False, 'backdrop_path': '/fUC5VsQcU3m6zmYMD96R7RqPuMn.jpg', 'genre_ids': [28, 80, 53], 'id': 1105407, 'original_language': 'en', 'original_title': 'Damaged', 'overview': 'A Chicago detective travels to Scotland after an emerging serial killer’s crimes match those that he investigated five years earlier, one of which was the crime scene of his murdered girlfriend.', 'popularity': 764.101, 'poster_path': '/tMO0YLXgJZBnIAjoTSz26zE33YN.jpg', 'release_date': '2024-04-12', 'title': 'Damaged', 'video': False, 'vote_average': 4.9, 'vote_count': 51}, {'adult': False, 'backdrop_path': '/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg', 'genre_ids': [878, 28, 14, 12], 'id': 601796, 'original_language': 'ko', 'original_title': '외계+인 1부', 'overview': "Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human's body. The two parties cross paths when a time-traveling portal opens up.", 'popularity': 656.511, 'poster_path': '/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg', 'release_date': '2024-03-20', 'title': 'Alienoid', 'video': False, 'vote_average': 6.799, 'vote_count': 298}, {'adult': False, 'backdrop_path': '/keVfqCMKmJ55nHzmqR2Q5K7LwJt.jpg', 'genre_ids': [28, 53, 10752], 'id': 784651, 'original_language': 'hi', 'original_title': 'फाइटर', 'overview': 'Top IAF aviators come together in the face of imminent danger, to form Air Dragons. Fighter unfolds their camaraderie, brotherhood and battles, internal and external.', 'popularity': 648.044, 'poster_path': '/zDZowwb9GZGEctAu2PCpjiPQAMM.jpg', 'release_date': '2024-01-26', 'title': 'Fighter', 'video': False, 'vote_average': 5.302, 'vote_count': 48}, {'adult': False, 'backdrop_path': '/oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg', 'genre_ids': [28, 53], 'id': 359410, 'original_language': 'en', 'original_title': 'Road House', 'overview': 'Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.', 'popularity': 634.211, 'poster_path': '/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg', 'release_date': '2024-03-21', 'title': 'Road House', 'video': False, 'vote_average': 7.02, 'vote_count': 1624}, {'adult': False, 'backdrop_path': '/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg', 'genre_ids': [16, 28, 12, 35, 10751], 'id': 940551, 'original_language': 'en', 'original_title': 'Migration', 'overview': 'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.', 'popularity': 640.652, 'poster_path': '/ldfCF9RhR40mppkzmftxapaHeTo.jpg', 'release_date': '2023-12-22', 'title': 'Migration', 'video': False, 'vote_average': 7.515, 'vote_count': 1256}, {'adult': False, 'backdrop_path': '/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg', 'genre_ids': [16, 878, 28], 'id': 1209288, 'original_language': 'en', 'original_title': 'Justice League: Crisis on Infinite Earths Part Two', 'overview': 'An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?', 'popularity': 622.207, 'poster_path': '/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg', 'release_date': '2024-04-22', 'title': 'Justice League: Crisis on Infinite Earths Part Two', 'video': False, 'vote_average': 6.477, 'vote_count': 44}, {'adult': False, 'backdrop_path': '/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg', 'genre_ids': [28, 14], 'id': 634492, 'original_language': 'en', 'original_title': 'Madame Web', 'overview': 'Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.', 'popularity': 702.779, 'poster_path': '/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg', 'release_date': '2024-02-14', 'title': 'Madame Web', 'video': False, 'vote_average': 5.612, 'vote_count': 1173}, {'adult': False, 'backdrop_path': '/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg', 'genre_ids': [28, 53], 'id': 984324, 'original_language': 'fr', 'original_title': 'Le salaire de la peur', 'overview': 'When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.', 'popularity': 497.077, 'poster_path': '/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg', 'release_date': '2024-03-29', 'title': 'The Wages of Fear', 'video': False, 'vote_average': 5.738, 'vote_count': 204}, {'adult': False, 'backdrop_path': '/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg', 'genre_ids': [18, 10749], 'id': 937287, 'original_language': 'en', 'original_title': 'Challengers', 'overview': 'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.', 'popularity': 653.009, 'poster_path': '/H6vke7zGiuLsz4v4RPeReb9rsv.jpg', 'release_date': '2024-04-26', 'title': 'Challengers', 'video': False, 'vote_average': 7.465, 'vote_count': 231}, {'adult': False, 'backdrop_path': '/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg', 'genre_ids': [10752, 28, 18], 'id': 929590, 'original_language': 'en', 'original_title': 'Civil War', 'overview': 'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.', 'popularity': 620.061, 'poster_path': '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg', 'release_date': '2024-04-19', 'title': 'Civil War', 'video': False, 'vote_average': 7.44, 'vote_count': 501}], 'total_pages': 43892, 'total_results': 877827}

PRUEBAS 20/03/24

In [8]:
import requests

url = "https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc"

headers = {
    "accept": "application/json",
    "Authorization": ""
}

response = requests.get(url, headers=headers)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/4woSOUD0equAYzvwhWBHIJDCM88.jpg","genre_ids":[28,27,53],"id":1096197,"original_language":"en","original_title":"No Way Up","overview":"Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.","popularity":1532.906,"poster_path":"/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg","release_date":"2024-01-18","title":"No Way Up","video":false,"vote_average":6.489,"vote_count":498},{"adult":false,"backdrop_path":"/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg","genre_ids":[28,878,12],"id":823464,"original_language":"en","original_title":"Godzilla x Kong: The New Empire","overview":"Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.","popularity":1611.66,"poster_path":"/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg","release_date":"2024-03-27","title":"Godzilla x Kong: The New Empire","video":false,"vote_average":6.633,"vote_count":811},{"adult":false,"backdrop_path":"/FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg","genre_ids":[878,28,18],"id":934632,"original_language":"en","original_title":"Rebel Moon - Part Two: The Scargiver","overview":"The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.","popularity":1523.65,"poster_path":"/cxevDYdeFkiixRShbObdwAHBZry.jpg","release_date":"2024-04-19","title":"Rebel Moon - Part Two: The Scargiver","video":false,"vote_average":6.158,"vote_count":573},{"adult":false,"backdrop_path":"/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg","genre_ids":[878,12],"id":693134,"original_language":"en","original_title":"Dune: Part Two","overview":"Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.","popularity":1488.917,"poster_path":"/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg","release_date":"2024-02-27","title":"Dune: Part Two","video":false,"vote_average":8.261,"vote_count":3473},{"adult":false,"backdrop_path":"/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg","genre_ids":[16,28,10751,35,14],"id":1011985,"original_language":"en","original_title":"Kung Fu Panda 4","overview":"Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.","popularity":1347.411,"poster_path":"/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg","release_date":"2024-03-02","title":"Kung Fu Panda 4","video":false,"vote_average":7.158,"vote_count":1400},{"adult":false,"backdrop_path":"/jnE1GA7cGEfv5DJBoU2t4bZHaP4.jpg","genre_ids":[28,878],"id":1094844,"original_language":"en","original_title":"Ape vs. Mecha Ape","overview":"Recognizing the destructive power of its captive giant Ape, the military makes its own battle-ready A.I., Mecha Ape. But its first practical test goes horribly wrong, leaving the military no choice but to release the imprisoned giant ape to stop the colossal robot before it destroys downtown Chicago.","popularity":1540.785,"poster_path":"/dJaIw8OgACelojyV6YuVsOhtTLO.jpg","release_date":"2023-03-24","title":"Ape vs. Mecha Ape","video":false,"vote_average":5.625,"vote_count":20},{"adult":false,"backdrop_path":"/5Eip60UDiPLASyKjmHPMruggTc4.jpg","genre_ids":[27,9648,53],"id":1041613,"original_language":"en","original_title":"Immaculate","overview":"An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.","popularity":883.669,"poster_path":"/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg","release_date":"2024-03-20","title":"Immaculate","video":false,"vote_average":6.277,"vote_count":323},{"adult":false,"backdrop_path":"/ilK1JRbMjo4sMJtNKLOKnqRf1RH.jpg","genre_ids":[10752,28,36],"id":976906,"original_language":"en","original_title":"Spitfire Over Berlin","overview":"August 1944. With the American Eighth Air Force poised to strike over Nazi Germany, British Intelligence learns that they could be flying into a deadly trap. With only hours to spare, Flight Lieutenant Edward Barnes must fly a life and death mission over Berlin in his unarmed Spitfire to obtain photographic evidence and save the lives of 1200 men.","popularity":815.831,"poster_path":"/xtPPOPTad1qopK6uDe3VlYUa22o.jpg","release_date":"2022-05-13","title":"Spitfire Over Berlin","video":false,"vote_average":3.615,"vote_count":13},{"adult":false,"backdrop_path":"/qnVm19Vu2Sc14LoEj82pmqAYr3p.jpg","genre_ids":[12,28,18],"id":845111,"original_language":"fr","original_title":"Les trois mousquetaires : Milady","overview":"D'Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.","popularity":842.014,"poster_path":"/rtosxP5sXuoRFPH4sVbMccLIPiV.jpg","release_date":"2023-12-13","title":"The Three Musketeers: Milady","video":false,"vote_average":6.558,"vote_count":356},{"adult":false,"backdrop_path":"/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg","genre_ids":[18,12],"id":618588,"original_language":"en","original_title":"Arthur the King","overview":"Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.","popularity":756.591,"poster_path":"/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg","release_date":"2024-03-15","title":"Arthur the King","video":false,"vote_average":6.682,"vote_count":73},{"adult":false,"backdrop_path":"/fUC5VsQcU3m6zmYMD96R7RqPuMn.jpg","genre_ids":[28,80,53],"id":1105407,"original_language":"en","original_title":"Damaged","overview":"A Chicago detective travels to Scotland after an emerging serial killer’s crimes match those that he investigated five years earlier, one of which was the crime scene of his murdered girlfriend.","popularity":764.101,"poster_path":"/tMO0YLXgJZBnIAjoTSz26zE33YN.jpg","release_date":"2024-04-12","title":"Damaged","video":false,"vote_average":4.9,"vote_count":51},{"adult":false,"backdrop_path":"/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg","genre_ids":[878,28,14,12],"id":601796,"original_language":"ko","original_title":"외계+인 1부","overview":"Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human's body. The two parties cross paths when a time-traveling portal opens up.","popularity":656.511,"poster_path":"/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg","release_date":"2022-07-20","title":"Alienoid","video":false,"vote_average":6.799,"vote_count":298},{"adult":false,"backdrop_path":"/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg","genre_ids":[28,14],"id":634492,"original_language":"en","original_title":"Madame Web","overview":"Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.","popularity":702.779,"poster_path":"/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg","release_date":"2024-02-14","title":"Madame Web","video":false,"vote_average":5.608,"vote_count":1172},{"adult":false,"backdrop_path":"/keVfqCMKmJ55nHzmqR2Q5K7LwJt.jpg","genre_ids":[28,53,10752],"id":784651,"original_language":"hi","original_title":"फाइटर","overview":"Top IAF aviators come together in the face of imminent danger, to form Air Dragons. Fighter unfolds their camaraderie, brotherhood and battles, internal and external.","popularity":648.044,"poster_path":"/zDZowwb9GZGEctAu2PCpjiPQAMM.jpg","release_date":"2024-01-24","title":"Fighter","video":false,"vote_average":5.302,"vote_count":48},{"adult":false,"backdrop_path":"/oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg","genre_ids":[28,53],"id":359410,"original_language":"en","original_title":"Road House","overview":"Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.","popularity":634.211,"poster_path":"/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg","release_date":"2024-03-08","title":"Road House","video":false,"vote_average":7.02,"vote_count":1624},{"adult":false,"backdrop_path":"/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg","genre_ids":[16,28,12,35,10751],"id":940551,"original_language":"en","original_title":"Migration","overview":"After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.","popularity":640.652,"poster_path":"/ldfCF9RhR40mppkzmftxapaHeTo.jpg","release_date":"2023-12-06","title":"Migration","video":false,"vote_average":7.516,"vote_count":1255},{"adult":false,"backdrop_path":"/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg","genre_ids":[16,878,28],"id":1209288,"original_language":"en","original_title":"Justice League: Crisis on Infinite Earths Part Two","overview":"An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?","popularity":622.207,"poster_path":"/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg","release_date":"2024-04-22","title":"Justice League: Crisis on Infinite Earths Part Two","video":false,"vote_average":6.395,"vote_count":43},{"adult":false,"backdrop_path":"/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg","genre_ids":[28,53],"id":984324,"original_language":"fr","original_title":"Le salaire de la peur","overview":"When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.","popularity":497.077,"poster_path":"/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg","release_date":"2024-03-28","title":"The Wages of Fear","video":false,"vote_average":5.738,"vote_count":204},{"adult":false,"backdrop_path":"/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg","genre_ids":[10752,28,18],"id":929590,"original_language":"en","original_title":"Civil War","overview":"In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.","popularity":620.061,"poster_path":"/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg","release_date":"2024-04-10","title":"Civil War","video":false,"vote_average":7.437,"vote_count":500},{"adult":false,"backdrop_path":"/9wJO4MBzkqgUZemLTGEsgUbYyP6.jpg","genre_ids":[878,9648,53],"id":720321,"original_language":"en","original_title":"Breathe","overview":"Air-supply is scarce in the near future, forcing a mother and daughter to fight for survival when two strangers arrive desperate for an oxygenated haven.","popularity":511.576,"poster_path":"/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg","release_date":"2024-04-04","title":"Breathe","video":false,"vote_average":5.0,"vote_count":60}],"total_pages":43889,"total_results":877765}

In [9]:
#ahora paso esta información a un dataframe: 

import requests
import pandas as pd

url = "https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc"

headers = {
    "accept": "application/json",
    "Authorization": ""
}

response = requests.get(url, headers=headers)

#verifico si sale bien
if response.status_code == 200:
    data = response.json()  #respuesta en formato JSON a un diccionario Python
    #extraigo lista de resultados
    results = data.get('results', [])
    #convierto la lista de resultados en un df de pandas
    df = pd.DataFrame(results)
    #imprimo
    print(df)
else:
    print("Error en la solicitud:", response.status_code)

    adult                     backdrop_path                genre_ids       id  \
0   False  /4woSOUD0equAYzvwhWBHIJDCM88.jpg             [28, 27, 53]  1096197
1   False  /qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg            [28, 878, 12]   823464
2   False   /FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg            [878, 28, 18]   934632
3   False  /xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg                [878, 12]   693134
4   False  /1XDDXPXGiI8id7MrUxK36ke7gkX.jpg  [16, 28, 10751, 35, 14]  1011985
5   False  /jnE1GA7cGEfv5DJBoU2t4bZHaP4.jpg                [28, 878]  1094844
6   False  /5Eip60UDiPLASyKjmHPMruggTc4.jpg           [27, 9648, 53]  1041613
7   False  /ilK1JRbMjo4sMJtNKLOKnqRf1RH.jpg          [10752, 28, 36]   976906
8   False  /qnVm19Vu2Sc14LoEj82pmqAYr3p.jpg             [12, 28, 18]   845111
9   False  /vTlK3chwsEToSoQJYUcJaHlNhIf.jpg                 [18, 12]   618588
10  False  /fUC5VsQcU3m6zmYMD96R7RqPuMn.jpg             [28, 80, 53]  1105407
11  False  /7ZP8HtgOIDaBs12krXgUIygqEsy.jpg        [878, 28, 14, 12]   601796
12  False  /pwGmXVKUgKN13psUjlhC9zBcq1o.jpg                 [28, 14]   634492
13  False  /keVfqCMKmJ55nHzmqR2Q5K7LwJt.jpg          [28, 53, 10752]   784651
14  False  /oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg                 [28, 53]   359410
15  False  /2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg  [16, 28, 12, 35, 10751]   940551
16  False  /tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg            [16, 878, 28]  1209288
17  False  /qekky2LbtT1wtbD5MDgQvjfZQ24.jpg                 [28, 53]   984324
18  False  /uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg          [10752, 28, 18]   929590
19  False  /9wJO4MBzkqgUZemLTGEsgUbYyP6.jpg          [878, 9648, 53]   720321

   original_language                                     original_title  \
0                 en                                          No Way Up
1                 en                    Godzilla x Kong: The New Empire
2                 en               Rebel Moon - Part Two: The Scargiver
3                 en                                     Dune: Part Two
4                 en                                    Kung Fu Panda 4
5                 en                                  Ape vs. Mecha Ape
6                 en                                         Immaculate
7                 en                               Spitfire Over Berlin
8                 fr                   Les trois mousquetaires : Milady
9                 en                                    Arthur the King
10                en                                            Damaged
11                ko                                            외계+인 1부
12                en                                         Madame Web
13                hi                                              फाइटर
14                en                                         Road House
15                en                                          Migration
16                en  Justice League: Crisis on Infinite Earths Part...
17                fr                              Le salaire de la peur
18                en                                          Civil War
19                en                                            Breathe

                                             overview  popularity  \
0   Characters from different backgrounds are thro...    1532.906
1   Following their explosive showdown, Godzilla a...    1611.660
2   The rebels gear up for battle against the ruth...    1523.650
3   Follow the mythic journey of Paul Atreides as ...    1488.917
4   Po is gearing up to become the spiritual leade...    1347.411
5   Recognizing the destructive power of its capti...    1540.785
6   An American nun embarks on a new journey when ...     883.669
7   August 1944. With the American Eighth Air Forc...     815.831
8   D'Artagnan, on a quest to rescue the abducted ...     842.014
9   Over the course of ten days and 435 miles, an ...     756.591
10  A Chicago detective travels to Scotland after ...     764.101
11  Gurus in the late Goryeo dynasty try to obtain...     656.511
12  Forced to confront revelations about her past,...     702.779
13  Top IAF aviators come together in the face of ...     648.044
14  Ex-UFC fighter Dalton takes a job as a bouncer...     634.211
15  After a migrating duck family alights on their...     640.652
16  An endless army of shadow demons bent on the d...     622.207
17  When an explosion at an oil well threatens hun...     497.077
18  In the near future, a group of war journalists...     620.061
19  Air-supply is scarce in the near future, forci...     511.576

                         poster_path release_date  \
0   /hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg   2024-01-18
1   /bQ2ywkchIiaKLSEaMrcT6e29f91.jpg   2024-03-27
2   /cxevDYdeFkiixRShbObdwAHBZry.jpg   2024-04-19
3   /1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg   2024-02-27
4   /kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg   2024-03-02
5   /dJaIw8OgACelojyV6YuVsOhtTLO.jpg   2023-03-24
6   /fdZpvODTX5wwkD0ikZNaClE4AoW.jpg   2024-03-20
7   /xtPPOPTad1qopK6uDe3VlYUa22o.jpg   2022-05-13
8   /rtosxP5sXuoRFPH4sVbMccLIPiV.jpg   2023-12-13
9   /gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg   2024-03-15
10  /tMO0YLXgJZBnIAjoTSz26zE33YN.jpg   2024-04-12
11  /8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg   2022-07-20
12  /rULWuutDcN5NvtiZi4FRPzRYWSh.jpg   2024-02-14
13  /zDZowwb9GZGEctAu2PCpjiPQAMM.jpg   2024-01-24
14  /bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg   2024-03-08
15  /ldfCF9RhR40mppkzmftxapaHeTo.jpg   2023-12-06
16  /g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg   2024-04-22
17  /jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg   2024-03-28
18  /sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg   2024-04-10
19  /wTW2t8ocWDlHns8I7vQxuqkyK58.jpg   2024-04-04

                                                title  video  vote_average  \
0                                           No Way Up  False         6.489
1                     Godzilla x Kong: The New Empire  False         6.633
2                Rebel Moon - Part Two: The Scargiver  False         6.158
3                                      Dune: Part Two  False         8.261
4                                     Kung Fu Panda 4  False         7.158
5                                   Ape vs. Mecha Ape  False         5.625
6                                          Immaculate  False         6.277
7                                Spitfire Over Berlin  False         3.615
8                        The Three Musketeers: Milady  False         6.558
9                                     Arthur the King  False         6.682
10                                            Damaged  False         4.900
11                                           Alienoid  False         6.799
12                                         Madame Web  False         5.608
13                                            Fighter  False         5.302
14                                         Road House  False         7.020
15                                          Migration  False         7.516
16  Justice League: Crisis on Infinite Earths Part...  False         6.395
17                                  The Wages of Fear  False         5.738
18                                          Civil War  False         7.437
19                                            Breathe  False         5.000

    vote_count
0          498
1          811
2          573
3         3473
4         1400
5           20
6          323
7           13
8          356
9           73
10          51
11         298
12        1172
13          48
14        1624
15        1255
16          43
17         204
18         500
19          60

In [10]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/4woSOUD0equAYzvwhWBHIJDCM88.jpg,"[28, 27, 53]",1096197,en,No Way Up,Characters from different backgrounds are thro...,1532.906,/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg,2024-01-18,No Way Up,False,6.489,498
1,False,/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg,"[28, 878, 12]",823464,en,Godzilla x Kong: The New Empire,"Following their explosive showdown, Godzilla a...",1611.660,/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg,2024-03-27,Godzilla x Kong: The New Empire,False,6.633,811
2,False,/FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg,"[878, 28, 18]",934632,en,Rebel Moon - Part Two: The Scargiver,The rebels gear up for battle against the ruth...,1523.650,/cxevDYdeFkiixRShbObdwAHBZry.jpg,2024-04-19,Rebel Moon - Part Two: The Scargiver,False,6.158,573
3,False,/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg,"[878, 12]",693134,en,Dune: Part Two,Follow the mythic journey of Paul Atreides as ...,1488.917,/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg,2024-02-27,Dune: Part Two,False,8.261,3473
4,False,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,"[16, 28, 10751, 35, 14]",1011985,en,Kung Fu Panda 4,Po is gearing up to become the spiritual leade...,1347.411,/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg,2024-03-02,Kung Fu Panda 4,False,7.158,1400

In [11]:
df.count()

adult                20
backdrop_path        20
genre_ids            20
id                   20
original_language    20
original_title       20
overview             20
popularity           20
poster_path          20
release_date         20
title                20
video                20
vote_average         20
vote_count           20
dtype: int64

PELIS AÑO 2022:

In [12]:
import requests
import pandas as pd

base_url = "https://api.themoviedb.org/3/discover/movie"
params = {
    "include_adult": "false",
    "include_video": "false",
    "language": "en-US",
    "sort_by": "popularity.desc",
    "page": 1,  
    "year": 2022
}

headers = {
    "accept": "application/json",
    "Authorization": "Bearer 1YiI6IjY1ZjZhZmQzNjY0NjlhMDE3ZTdhNTkyNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.A5VdDbZhVZjV5J6iUvEWiF6WauWFOxzIK5H7Xbvc6Hc"
}

all_results = []  

while True:
    response = requests.get(base_url, headers=headers, params=params)

    if response.status_code == 200:
        data = response.json()  
        results = data.get('results', [])  
        all_results.extend(results)  
        total_pages = data.get('total_pages')  
        params['page'] += 1 

        if params['page'] > total_pages:  
            break
    else:
        print("Error en la solicitud:", response.status_code)
        break

df2022 = pd.DataFrame(all_results)
print(df2022)

Error en la solicitud: 400
      adult                     backdrop_path          genre_ids       id  \
0     False  /ilK1JRbMjo4sMJtNKLOKnqRf1RH.jpg    [10752, 28, 36]   976906
1     False  /7ZP8HtgOIDaBs12krXgUIygqEsy.jpg  [878, 28, 14, 12]   601796
2     False  /dcnSWFCtk4b2aIzkhq6IDbzoIf1.jpg           [28, 35]   942047
3     False  /lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg          [878, 12]   438631
4     False  /atPlFdUrQl2U9MtUwujrrjnQHBA.jpg   [28, 80, 18, 53]   654739
...     ...                               ...                ...      ...
9995  False  /mAx5aQFpvoZcLT7JrVmDfevH2Cs.jpg               [18]   940849
9996  False                              None                 []   933803
9997  False  /rgvI9BRtJtKLrYxl5jJ2wbpYhzX.jpg    [18, 10749, 53]   796155
9998  False  /g9eveG1Hi0qVXnCJAT7PGVL1Wx4.jpg               [28]    74605
9999  False                              None                 []  1065151

     original_language                                     original_title  \
0                   en                               Spitfire Over Berlin
1                   ko                                            외계+인 1부
2                   en                                          Outsource
3                   en                                               Dune
4                   ko                                               발신제한
...                ...                                                ...
9995                es                                         Corpúsculo
9996                fr                                             UDRIVE
9997                zh                                               青春弒戀
9998                it                             I pirati della Malesia
9999                en  The Great American Baking Show: Celebrity Holiday

                                               overview  popularity  \
0     August 1944. With the American Eighth Air Forc...     815.831
1     Gurus in the late Goryeo dynasty try to obtain...     656.511
2     A police chief hires an old friend, who is an ...     465.840
3     Paul Atreides, a brilliant and gifted young ma...     540.623
4     On his way to work, a bank manager receives an...     392.277
...                                                 ...         ...
9995  After an unidentified earthquake-like ground s...       4.791
9996  Jason, a young open-minded driver, works at Ud...       4.791
9997  The film is set in a pre-Covid Taipei, where a...       3.684
9998  Filmed in Singapore it tells the story of Sand...       4.789
9999  Six celebrities, 3 holiday-themed challenges, ...       2.052

                           poster_path release_date  \
0     /xtPPOPTad1qopK6uDe3VlYUa22o.jpg   2022-05-13
1     /8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg   2022-07-20
2     /zIAF0UXtCJTJOYNYWiBfyifaaOi.jpg   2022-01-18
3     /d5NXSklXo0qyIYkgV94XAgMIckC.jpg   2021-09-15
4     /y2Aimt8isimtigec3e4kB2G9FMR.jpg   2021-06-23
...                                ...          ...
9995  /8CVnDRewBCWxFLnL95gFuj8rpD9.jpg   2022-10-22
9996  /aqWLBvIIrBCF4l9lGrbvFh7WBdx.jpg   2022-02-01
9997  /xsyo6c7sX0UYbGwvpiOfzx6PWoz.jpg   2021-11-19
9998  /22fIERshbW1b2MQvva0WPpDcgqd.jpg   1964-10-16
9999  /eUsq2LN10bnctGir5gQJ3iXDc0O.jpg   2022-12-02

                                                  title  video  vote_average  \
0                                  Spitfire Over Berlin  False         3.615
1                                              Alienoid  False         6.799
2                                             Outsource  False         2.300
3                                                  Dune  False         7.791
4                                              Hard Hit  False         7.700
...                                                 ...    ...           ...
9995                                         Corpúsculo  False         3.000
9996                                             UDRIVE  False         0.000
9997                                        Terrorizers  False         6.000
9998                            The Pirates of Malaysia  False         4.500
9999  The Great American Baking Show: Celebrity Holiday  False         0.000

      vote_count
0             13
1            298
2             11
3          11444
4            174
...          ...
9995           1
9996           0
9997           5
9998           9
9999           0

[10000 rows x 14 columns]

PELIS 2021

In [13]:
import requests
import pandas as pd

base_url = "https://api.themoviedb.org/3/discover/movie"
params = {
    "include_adult": "false",
    "include_video": "false",
    "language": "en-US",
    "sort_by": "popularity.desc",
    "page": 1,  
    "year": 2021  
}

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJh1YiI6IjY1ZjZhZmyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.A5VdDbZhVZjV5J6iUvEWiF6WauWFOxzIK5H7Xbvc6Hc"
}

all_results = []  

while True:
    response = requests.get(base_url, headers=headers, params=params)

    if response.status_code == 200:
        data = response.json()  
        results = data.get('results', [])  # Indentación corregida
        all_results.extend(results)  
        total_pages = data.get('total_pages')  
        params['page'] += 1 

        if params['page'] > total_pages:  
            break
    else:
        print("Error en la solicitud:", response.status_code)
        break

df2021 = pd.DataFrame(all_results)
print(df2021)

Error en la solicitud: 400
      adult                     backdrop_path         genre_ids       id  \
0     False  /lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg         [878, 12]   438631
1     False  /atPlFdUrQl2U9MtUwujrrjnQHBA.jpg  [28, 80, 18, 53]   654739
2     False  /en971MEXui9diirXlogOrPKmsEn.jpg      [28, 12, 35]   293660
3     False  /3RWsSQlqzRjsuqSRmoyggy74UA7.jpg      [28, 14, 35]    43074
4     False  /yY76zq9XSuJ4nWyPDuwkdV7Wt0c.jpg     [28, 53, 878]   577922
...     ...                               ...               ...      ...
9995  False                              None              [27]  1144528
9996  False  /c9fbOEI6kJw5Eq8NHG2qR5VG70A.jpg                []   934835
9997  False  /swaI8REF35bEK8LJtUS22nOHaiZ.jpg          [35, 99]   892051
9998  False  /5Nx7qfVpRGeOPE542WZMghTVpfH.jpg              [18]   876674
9999  False  /uOIgvDMJ15zofF8bb40wsZpNyk1.jpg              [35]    43206

     original_language        original_title  \
0                   en                  Dune
1                   ko                  발신제한
2                   en              Deadpool
3                   en          Ghostbusters
4                   en                 Tenet
...                ...                   ...
9995                en            Discharged
9996                hu                  JHVH
9997                en  Christmas In Florida
9998                de            Verbindung
9999                no          Pitbullterje

                                               overview  popularity  \
0     Paul Atreides, a brilliant and gifted young ma...     540.623
1     On his way to work, a bank manager receives an...     392.277
2     The origin story of former Special Forces oper...     454.956
3     Following a ghost invasion of Manhattan, paran...     454.747
4     Armed with only one word - Tenet - and fightin...     433.928
...                                                 ...         ...
9995  Norman has finally been discharged. You'll nev...       3.065
9996  Juli's mother is a strict religious person and...       2.843
9997  A canceled Thanksgiving parade and no options ...       2.376
9998  David is a member of a student fraternity. Cor...       3.594
9999  Jim is a 12-year-old outsider. One day Terje (...       3.217

                           poster_path release_date                 title  \
0     /d5NXSklXo0qyIYkgV94XAgMIckC.jpg   2021-09-15                  Dune
1     /y2Aimt8isimtigec3e4kB2G9FMR.jpg   2021-06-23              Hard Hit
2     /fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg   2016-02-09              Deadpool
3     /wJmWliwXIgZOCCVOcGRBhce7xPS.jpg   2016-07-14          Ghostbusters
4     /k68nPLbIST6NP96JmTxmZijEvCA.jpg   2020-08-22                 Tenet
...                                ...          ...                   ...
9995  /jq3ZpGg1faEmg8HnMH3gagXuvZq.jpg   2021-09-09            Discharged
9996  /6mLjDVJXeoS3v9DSg7dyKEktBmA.jpg   2021-06-18                  JHVH
9997  /dSuux1sf8ufWkThQuPElU8bXJDY.jpg   2021-11-01  Christmas In Florida
9998  /vC5QlM44o88LZdXin8ot02ykpXI.jpg   2021-08-01            Verbindung
9999  /vE0HfaQCq9dNAIPfLvizkqBSp1y.jpg   2005-11-04          Pitbullterje

      video  vote_average  vote_count
0     False         7.790       11445
1     False         7.700         174
2     False         7.612       29802
3     False         5.360        6186
4     False         7.184        9333
...     ...           ...         ...
9995  False         0.000           0
9996  False        10.000           1
9997  False         5.500           2
9998  False         4.000           1
9999  False         5.500          14

[10000 rows x 14 columns]

PELIS 2020

In [14]:
import requests
import pandas as pd

base_url = "https://api.themoviedb.org/3/discover/movie"
params = {
    "include_adult": "false",
    "include_video": "false",
    "language": "en-US",
    "sort_by": "popularity.desc",
    "page": 1,  
    "year": 2020  
}

headers = {
    "accept": "application/json",
    "Authorization": "Bearer I6IjY1ZjZhZmQzNjY0NjlhMDE3ZTdhNTkyNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.A5VdDbZhVZjV5J6iUvEWiF6WauWFOxzIK5H7Xbvc6Hc"
}

all_results = []  

while True:
    response = requests.get(base_url, headers=headers, params=params)

    if response.status_code == 200:
        data = response.json()  
        results = data.get('results', [])  # Indentación corregida
        all_results.extend(results)  
        total_pages = data.get('total_pages')  
        params['page'] += 1 

        if params['page'] > total_pages:  
            break
    else:
        print("Error en la solicitud:", response.status_code)
        break

df2020 = pd.DataFrame(all_results)
print(df2020)

Error en la solicitud: 400
      adult                     backdrop_path      genre_ids      id  \
0     False  /en971MEXui9diirXlogOrPKmsEn.jpg   [28, 12, 35]  293660
1     False  /3RWsSQlqzRjsuqSRmoyggy74UA7.jpg   [28, 14, 35]   43074
2     False  /yY76zq9XSuJ4nWyPDuwkdV7Wt0c.jpg  [28, 53, 878]  577922
3     False  /n6bUvigpRFqSwmPp1m2YADdbRBc.jpg   [80, 53, 18]  475557
4     False  /qAzYK4YPSWDc7aa4R43LcwRIAyb.jpg  [28, 12, 878]  299537
...     ...                               ...            ...     ...
9995  False                              None           [18]  746288
9996  False                              None      [35, 878]  743488
9997  False                              None             []  743117
9998  False                              None           [18]  742763
9999  False                              None           [18]  742519

     original_language        original_title  \
0                   en              Deadpool
1                   en          Ghostbusters
2                   en                 Tenet
3                   en                 Joker
4                   en        Captain Marvel
...                ...                   ...
9995                en              Last Day
9996                en              Comisery
9997                en  A Half Painted House
9998                en       Absent Thoughts
9999                id               Ruwatan

                                               overview  popularity  \
0     The origin story of former Special Forces oper...     454.956
1     Following a ghost invasion of Manhattan, paran...     454.747
2     Armed with only one word - Tenet - and fightin...     433.928
3     During the 1980s, a failed stand-up comedian i...     445.021
4     The story follows Carol Danvers as she becomes...     402.219
...                                                 ...         ...
9995  As work continues on the border wall, a Chines...       3.842
9996  An apocalyptic science fiction comedy told ent...       3.842
9997  A priest’s tragic end offers insight into his ...       1.646
9998  Richard Has A Secret. A Secret That Has Shaped...       3.842
9999  Accompanying her blind mother undergo alternat...       3.842

                           poster_path release_date                 title  \
0     /fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg   2016-02-09              Deadpool
1     /wJmWliwXIgZOCCVOcGRBhce7xPS.jpg   2016-07-14          Ghostbusters
2     /k68nPLbIST6NP96JmTxmZijEvCA.jpg   2020-08-22                 Tenet
3     /udDclJoHjfjb8Ekgsd4FDteOkCU.jpg   2019-10-01                 Joker
4     /AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg   2019-03-06        Captain Marvel
...                                ...          ...                   ...
9995                              None   2020-06-14              Last Day
9996  /2lCJVHbr1i0W1vbEDGQoicXdW75.jpg   2020-09-01              Comisery
9997  /acKyAUZFZdXMZe8cKSNHP6eEMCd.jpg   2020-08-28  A Half Painted House
9998  /30IV5UXcACOSuK204CLaL3CAZNx.jpg   2020-09-02       Absent Thoughts
9999  /sdXmhj8OxdqJ5jZ4le4fDdUMnEE.jpg   2020-09-16               Ruwatan

      video  vote_average  vote_count
0     False         7.612       29802
1     False         5.360        6186
2     False         7.184        9333
3     False         8.162       24495
4     False         6.825       15227
...     ...           ...         ...
9995  False         0.000           0
9996  False         0.000           0
9997  False         0.000           0
9998  False        10.000           1
9999  False         0.000           0

[10000 rows x 14 columns]

In [15]:
df2020.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/en971MEXui9diirXlogOrPKmsEn.jpg,"[28, 12, 35]",293660,en,Deadpool,The origin story of former Special Forces oper...,454.956,/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg,2016-02-09,Deadpool,False,7.612,29802
1,False,/3RWsSQlqzRjsuqSRmoyggy74UA7.jpg,"[28, 14, 35]",43074,en,Ghostbusters,"Following a ghost invasion of Manhattan, paran...",454.747,/wJmWliwXIgZOCCVOcGRBhce7xPS.jpg,2016-07-14,Ghostbusters,False,5.360,6186
2,False,/yY76zq9XSuJ4nWyPDuwkdV7Wt0c.jpg,"[28, 53, 878]",577922,en,Tenet,Armed with only one word - Tenet - and fightin...,433.928,/k68nPLbIST6NP96JmTxmZijEvCA.jpg,2020-08-22,Tenet,False,7.184,9333
3,False,/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg,"[80, 53, 18]",475557,en,Joker,"During the 1980s, a failed stand-up comedian i...",445.021,/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg,2019-10-01,Joker,False,8.162,24495
4,False,/qAzYK4YPSWDc7aa4R43LcwRIAyb.jpg,"[28, 12, 878]",299537,en,Captain Marvel,The story follows Carol Danvers as she becomes...,402.219,/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg,2019-03-06,Captain Marvel,False,6.825,15227

In [16]:
import requests
import pandas as pd

base_url = "https://api.themoviedb.org/3/discover/movie"
params = {
    "include_adult": "false",
    "include_video": "false",
    "language": "en-US",
    "sort_by": "popularity.desc",
    "page": 1,  
    "year": 2019 
}

headers = {
    "accept": "application/json",
    "Authorization": "
all_results = []  

while True:
    response = requests.get(base_url, headers=headers, params=params)

    if response.status_code == 200:
        data = response.json()  
        results = data.get('results', [])  # Indentación corregida
        all_results.extend(results)  
        total_pages = data.get('total_pages')  
        params['page'] += 1 

        if params['page'] > total_pages:  
            break
    else:
        print("Error en la solicitud:", response.status_code)
        break

df2019 = pd.DataFrame(all_results)
print(df2019)

Error en la solicitud: 400
      adult                     backdrop_path       genre_ids       id  \
0     False  /n6bUvigpRFqSwmPp1m2YADdbRBc.jpg    [80, 53, 18]   475557
1     False  /qAzYK4YPSWDc7aa4R43LcwRIAyb.jpg   [28, 12, 878]   299537
2     False  /9X7YweCJw3q8Mcf6GadxReFEksM.jpg   [28, 18, 878]   263115
3     False  /8K9qHeM6G6QjQN0C5XKFGvK5lzM.jpg       [28, 878]      603
4     False  /hdHIjZxq3SWFqpAz4NFhdbud0iz.jpg       [27, 878]      348
...     ...                               ...             ...      ...
9995  False                              None              []   608098
9996  False  /rgHhV67uLbQzZ7dbUuB89CiZrhp.jpg            [99]   391719
9997  False  /8RVQ3QeSej8tfX4HhPC3I1BkhzD.jpg  [80, 9648, 53]   674207
9998  False                              None            [18]  1277580
9999  False                              None            [35]   700133

     original_language                                 original_title  \
0                   en                                          Joker
1                   en                                 Captain Marvel
2                   en                                          Logan
3                   en                                     The Matrix
4                   en                                          Alien
...                ...                                            ...
9995                fr                                      Quatrième
9996                en  The Secret Rules of Modern Living: Algorithms
9997                en                                     Hollywould
9998                en                                      The Shore
9999                fr                                          Akram

                                               overview  popularity  \
0     During the 1980s, a failed stand-up comedian i...     445.021
1     The story follows Carol Danvers as she becomes...     402.219
2     In the near future, a weary Logan cares for an...     412.050
3     Set in the 22nd century, The Matrix tells the ...     404.500
4     During its return to the earth, commercial spa...     364.310
...                                                 ...         ...
9995                                                          4.026
9996  Without us noticing, modern life has been take...       2.686
9997  Award winning writer, celebrity Mark Travis se...       3.000
9998                                                          4.024
9999  While looking for his concert outfit, Alexande...       4.024

                           poster_path release_date  \
0     /udDclJoHjfjb8Ekgsd4FDteOkCU.jpg   2019-10-01
1     /AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg   2019-03-06
2     /fnbjcRDYn6YviCcePDnGdyAkYsB.jpg   2017-02-28
3     /f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg   1999-03-31
4     /vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg   1979-05-25
...                                ...          ...
9995                              None   2019-06-10
9996  /17AEcWyF7zhVtmVOSoMhxIaNchC.jpg   2015-09-24
9997   /dTQ4zUaUb3eFjWsq7uVYmDQFwB.jpg   2019-04-25
9998                              None   2019-01-01
9999   /tBirt8pEhjSS7hIrJw8boI0SfW.jpg   2019-01-01

                                              title  video  vote_average  \
0                                             Joker  False         8.162
1                                    Captain Marvel  False         6.825
2                                             Logan  False         7.817
3                                        The Matrix  False         8.214
4                                             Alien  False         8.152
...                                             ...    ...           ...
9995                                      Quatrième  False         0.000
9996  The Secret Rules of Modern Living: Algorithms  False         7.500
9997                                     Hollywould  False        10.000
9998                                      The Shore  False         0.000
9999                                          Akram  False         0.000

      vote_count
0          24495
1          15227
2          18638
3          24810
4          13879
...          ...
9995           0
9996          25
9997           2
9998           0
9999           0

[10000 rows x 14 columns]

In [17]:
import requests
import pandas as pd

base_url = "https://api.themoviedb.org/3/discover/movie"
params = {
    "include_adult": "false",
    "include_video": "false",
    "language": "en-US",
    "sort_by": "popularity.desc",
    "page": 1,  
    "year": 2018 
}

headers = {
    "accept": "application/json",
    "Authorization": "BnN1YiI6IjY1ZjZhZmQzNjY0NjlhMDE3ZTdhNTkyNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.A5VdDbZhVZjV5J6iUvEWiF6WauWFOxzIK5H7Xbvc6Hc"
}

all_results = []  

while True:
    response = requests.get(base_url, headers=headers, params=params)

    if response.status_code == 200:
        data = response.json()  
        results = data.get('results', [])  # Indentación corregida
        all_results.extend(results)  
        total_pages = data.get('total_pages')  
        params['page'] += 1 

        if params['page'] > total_pages:  
            break
    else:
        print("Error en la solicitud:", response.status_code)
        break

df2018 = pd.DataFrame(all_results)
print(df2018)

Error en la solicitud: 400
      adult                     backdrop_path      genre_ids      id  \
0     False  /en971MEXui9diirXlogOrPKmsEn.jpg   [28, 12, 35]  293660
1     False  /6iUNJZymJBMXXriQyFZfLAKnjO6.jpg   [28, 12, 14]  297762
2     False  /kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg  [28, 12, 878]  284053
3     False  /9X7YweCJw3q8Mcf6GadxReFEksM.jpg  [28, 18, 878]  263115
4     False  /8K9qHeM6G6QjQN0C5XKFGvK5lzM.jpg      [28, 878]     603
...     ...                               ...            ...     ...
9995  False  /4PsSs6qSeR2UTM0IPgzKNLu4WYJ.jpg    [10751, 35]  494642
9996  False                              None             []  713927
9997  False  /oNzQUAerCEtzS5FYPOoMTxgpauv.jpg           [18]  837765
9998  False  /csTScGuwj1vDCVKkGVxp59mTiwp.jpg  [878, 18, 35]  607886
9999  False  /7vdQ7b8WwcwRDXMf2EASZGYLM5t.jpg        [10402]  583886

     original_language   original_title  \
0                   en         Deadpool
1                   en     Wonder Woman
2                   en   Thor: Ragnarok
3                   en            Logan
4                   en       The Matrix
...                ...              ...
9995                cs  Nejlepší přítel
9996                da         Grøn top
9997                es           Abuelo
9998                en         Lifeline
9999                en      MFO Akustik

                                               overview  popularity  \
0     The origin story of former Special Forces oper...     454.956
1     An Amazon princess comes to the world of Man i...     393.794
2     Thor is imprisoned on the other side of the un...     393.367
3     In the near future, a weary Logan cares for an...     412.050
4     Set in the 22nd century, The Matrix tells the ...     404.500
...                                                 ...         ...
9995                                                          2.388
9996                                                          3.648
9997                                                          3.647
9998  A nervous job candidate is forced to show much...       3.647
9999                       MFO live at TRT Music studio       3.647

                           poster_path release_date            title  video  \
0     /fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg   2016-02-09         Deadpool  False
1     /imekS7f1OuHyUP2LAiTEM0zBzUz.jpg   2017-05-30     Wonder Woman  False
2     /rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg   2017-10-02   Thor: Ragnarok  False
3     /fnbjcRDYn6YviCcePDnGdyAkYsB.jpg   2017-02-28            Logan  False
4     /f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg   1999-03-31       The Matrix  False
...                                ...          ...              ...    ...
9995  /pU5w0DIY1eGcEJRjgq7Vjrwx2tu.jpg   2017-12-24  Nejlepší přítel  False
9996  /4sNV4a6TguSY5UGALyonnqHTo75.jpg   2018-07-30         Grøn top  False
9997  /4CR5E2xAJ1pGOWsKOI8BfRvYRw0.jpg   2018-06-13      Grandfather  False
9998  /g08u8RmHJQw89oYzPZJxoJWAf5r.jpg   2018-10-19         Lifeline  False
9999  /uzxCJI9FfWfyNiDvJg72KKt49UI.jpg   2018-12-20      MFO Akustik  False

      vote_average  vote_count
0            7.612       29801
1            7.229       19475
2            7.592       20156
3            7.817       18638
4            8.214       24810
...            ...         ...
9995         7.700           8
9996         6.500           2
9997         7.000           1
9998         5.000           1
9999         0.000           0

[10000 rows x 14 columns]

In [18]:
import requests
import pandas as pd

base_url = "https://api.themoviedb.org/3/discover/movie"
params = {
    "include_adult": "false",
    "include_video": "false",
    "language": "en-US",
    "sort_by": "popularity.desc",
    "page": 1,  
    "year": 2017 
}

headers = {
    "accept": "application/json",
    "Authorization": "Bearer e
}

all_results = []  

while True:
    response = requests.get(base_url, headers=headers, params=params)

    if response.status_code == 200:
        data = response.json()  
        results = data.get('results', [])  # Indentación corregida
        all_results.extend(results)  
        total_pages = data.get('total_pages')  
        params['page'] += 1 

        if params['page'] > total_pages:  
            break
    else:
        print("Error en la solicitud:", response.status_code)
        break

df2017 = pd.DataFrame(all_results)
print(df2017)

Error en la solicitud: 400
      adult                     backdrop_path            genre_ids      id  \
0     False  /3RWsSQlqzRjsuqSRmoyggy74UA7.jpg         [28, 14, 35]   43074
1     False  /6iUNJZymJBMXXriQyFZfLAKnjO6.jpg         [28, 12, 14]  297762
2     False  /kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg        [28, 12, 878]  284053
3     False  /9X7YweCJw3q8Mcf6GadxReFEksM.jpg        [28, 18, 878]  263115
4     False  /xJHokMbljvjADYdit5fK5VQsXEG.jpg        [12, 18, 878]  157336
...     ...                               ...                  ...     ...
9995  False  /cI1245MAkh7wVsR1N1VHeOYa3Kr.jpg                 [35]  472225
9996  False  /z6JraWUlKop278ufanjBCpJu7Gr.jpg                 [18]  417264
9997  False  /oPzqqWEIgKfEds8hjMByUL6uS09.jpg  [16, 10751, 14, 35]  999332
9998  False                              None                 [99]  568834
9999  False                              None                 [99]  558052

     original_language                   original_title  \
0                   en                     Ghostbusters
1                   en                     Wonder Woman
2                   en                   Thor: Ragnarok
3                   en                            Logan
4                   en                     Interstellar
...                ...                              ...
9995                es  ¿Cómo matar a un esposo muerto?
9996                en               Tater Tot & Patton
9997                en                 Trolls: Dress Up
9998                de                 Heimat Helgoland
9999                it                     Raising Pino

                                               overview  popularity  \
0     Following a ghost invasion of Manhattan, paran...     454.747
1     An Amazon princess comes to the world of Man i...     393.794
2     Thor is imprisoned on the other side of the un...     393.367
3     In the near future, a weary Logan cares for an...     412.050
4     The adventures of a group of explorers who mak...     388.917
...                                                 ...         ...
9995  Carolina, married to Germán, decides to put an...       2.166
9996  A wayward millennial escapes to a South Dakota...       1.575
9997  A little bit of this and a little bit of that....       2.236
9998                                                          3.146
9999  An interview with composer Pino Donaggio talki...       3.632

                           poster_path release_date  \
0     /wJmWliwXIgZOCCVOcGRBhce7xPS.jpg   2016-07-14
1     /imekS7f1OuHyUP2LAiTEM0zBzUz.jpg   2017-05-30
2     /rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg   2017-10-02
3     /fnbjcRDYn6YviCcePDnGdyAkYsB.jpg   2017-02-28
4     /gEU2QniE6E77NI6lCU6MxlNBvIx.jpg   2014-11-05
...                                ...          ...
9995  /yZQbSUZTSL8jO8DN12XI2uhjAAV.jpg   2017-09-01
9996  /nltt8QDOf2uqgyeSacN15oEEcny.jpg   2017-06-09
9997  /kJNBjelCpSYwzWT40goADxk0AM3.jpg   2017-11-18
9998                              None   2017-10-03
9999  /40rSXTvl2eFgDTHJXQKDzqZoQy1.jpg   2017-01-30

                             title  video  vote_average  vote_count
0                     Ghostbusters  False         5.360        6186
1                     Wonder Woman  False         7.229       19475
2                   Thor: Ragnarok  False         7.592       20156
3                            Logan  False         7.817       18638
4                     Interstellar  False         8.433       34210
...                            ...    ...           ...         ...
9995  How to Murder a Dead Husband  False         3.800           9
9996            Tater Tot & Patton  False         5.800           6
9997              Trolls: Dress Up  False         7.800           3
9998              Heimat Helgoland  False         0.000           0
9999                  Raising Pino  False         0.000           0

[10000 rows x 14 columns]

In [19]:
import pandas as pd

#combino todos los DF para tener 1 final
df_años = pd.concat([df2017, df2018, df2019, df2020, df2021, df], ignore_index=True)

df_años.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/3RWsSQlqzRjsuqSRmoyggy74UA7.jpg,"[28, 14, 35]",43074,en,Ghostbusters,"Following a ghost invasion of Manhattan, paran...",454.747,/wJmWliwXIgZOCCVOcGRBhce7xPS.jpg,2016-07-14,Ghostbusters,False,5.360,6186
1,False,/6iUNJZymJBMXXriQyFZfLAKnjO6.jpg,"[28, 12, 14]",297762,en,Wonder Woman,An Amazon princess comes to the world of Man i...,393.794,/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg,2017-05-30,Wonder Woman,False,7.229,19475
2,False,/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg,"[28, 12, 878]",284053,en,Thor: Ragnarok,Thor is imprisoned on the other side of the un...,393.367,/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg,2017-10-02,Thor: Ragnarok,False,7.592,20156
3,False,/9X7YweCJw3q8Mcf6GadxReFEksM.jpg,"[28, 18, 878]",263115,en,Logan,"In the near future, a weary Logan cares for an...",412.050,/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg,2017-02-28,Logan,False,7.817,18638
4,False,/xJHokMbljvjADYdit5fK5VQsXEG.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,388.917,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,Interstellar,False,8.433,34210

In [26]:
df_años.tail()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
50015,False,/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg,"[16, 28, 12, 35, 10751]",940551,en,Migration,After a migrating duck family alights on their...,640.652,/ldfCF9RhR40mppkzmftxapaHeTo.jpg,2023-12-06,Migration,False,7.516,1255
50016,False,/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg,"[16, 878, 28]",1209288,en,Justice League: Crisis on Infinite Earths Part...,An endless army of shadow demons bent on the d...,622.207,/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg,2024-04-22,Justice League: Crisis on Infinite Earths Part...,False,6.395,43
50017,False,/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg,"[28, 53]",984324,fr,Le salaire de la peur,When an explosion at an oil well threatens hun...,497.077,/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg,2024-03-28,The Wages of Fear,False,5.738,204
50018,False,/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg,"[10752, 28, 18]",929590,en,Civil War,"In the near future, a group of war journalists...",620.061,/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg,2024-04-10,Civil War,False,7.437,500
50019,False,/9wJO4MBzkqgUZemLTGEsgUbYyP6.jpg,"[878, 9648, 53]",720321,en,Breathe,"Air-supply is scarce in the near future, forci...",511.576,/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg,2024-04-04,Breathe,False,5.000,60

In [173]:
import pandas as pd

#para no ejecutarlo todo cada vez que entro de nuevo, lo paso a un CSV
df_años.to_csv('df_años.csv', index=False)

In [177]:
#leo el CSV
df2 = pd.read_csv('df_años - copia.csv')

In [190]:
df2.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,...,video,vote_average,vote_count,columna1,columna2,columna3,columna4,columna5,columna6,columna7
0,False,/3RWsSQlqzRjsuqSRmoyggy74UA7.jpg,"[28, 14, 35]",43074,en,Ghostbusters,"Following a ghost invasion of Manhattan, paran...",454.747,/wJmWliwXIgZOCCVOcGRBhce7xPS.jpg,2016-07-14,...,False,5.360,6186,28,14,35,NaN,NaN,NaN,NaN
1,False,/6iUNJZymJBMXXriQyFZfLAKnjO6.jpg,"[28, 12, 14]",297762,en,Wonder Woman,An Amazon princess comes to the world of Man i...,393.794,/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg,2017-05-30,...,False,7.229,19475,28,12,14,NaN,NaN,NaN,NaN
2,False,/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg,"[28, 12, 878]",284053,en,Thor: Ragnarok,Thor is imprisoned on the other side of the un...,393.367,/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg,2017-10-02,...,False,7.592,20156,28,12,878,NaN,NaN,NaN,NaN
3,False,/9X7YweCJw3q8Mcf6GadxReFEksM.jpg,"[28, 18, 878]",263115,en,Logan,"In the near future, a weary Logan cares for an...",412.050,/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg,2017-02-28,...,False,7.817,18638,28,18,878,NaN,NaN,NaN,NaN
4,False,/xJHokMbljvjADYdit5fK5VQsXEG.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,388.917,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,...,False,8.433,34210,12,18,878,NaN,NaN,NaN,NaN

HASTA AQUÍ CÓDIGO EJECUTADO Y GUARDADO EN UN CSV

In [179]:
longitud_maxima = df2['genre_ids'].apply(len).max()

print("Longitud máxima de la lista más larga:", longitud_maxima)

Longitud máxima de la lista más larga: 40

In [180]:
fila_lista_mas_larga = df.loc[df2['genre_ids'].apply(len).idxmax()]

lista_mas_larga = fila_lista_mas_larga['genre_ids']

print("La lista más larga es:", lista_mas_larga)

La lista más larga es: [10751, 10402, 14, 10770, 12, 28, 10749]

In [181]:
df_separado = df2['genre_ids'].str.split(',').apply(lambda x: [e.strip('[]') for e in x]).apply(pd.Series)

#le pongo nombre a las columnas
column_names = ['columna{}'.format(i+1) for i in range(len(df_separado.columns))]
df_separado.columns = column_names

df2 = pd.concat([df, df_separado], axis=1)

df2

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,...,genero7,genero8,genero9,columna1,columna2,columna3,columna4,columna5,columna6,columna7
0,False,/3RWsSQlqzRjsuqSRmoyggy74UA7.jpg,"[28, 14, 35]",43074,en,Ghostbusters,"Following a ghost invasion of Manhattan, paran...",454.747,/wJmWliwXIgZOCCVOcGRBhce7xPS.jpg,2016-07-14,...,NaN,NaN,NaN,28,14,35,NaN,NaN,NaN,NaN
1,False,/6iUNJZymJBMXXriQyFZfLAKnjO6.jpg,"[28, 12, 14]",297762,en,Wonder Woman,An Amazon princess comes to the world of Man i...,393.794,/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg,2017-05-30,...,NaN,NaN,NaN,28,12,14,NaN,NaN,NaN,NaN
2,False,/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg,"[28, 12, 878]",284053,en,Thor: Ragnarok,Thor is imprisoned on the other side of the un...,393.367,/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg,2017-10-02,...,NaN,NaN,NaN,28,12,878,NaN,NaN,NaN,NaN
3,False,/9X7YweCJw3q8Mcf6GadxReFEksM.jpg,"[28, 18, 878]",263115,en,Logan,"In the near future, a weary Logan cares for an...",412.050,/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg,2017-02-28,...,NaN,NaN,NaN,28,18,878,NaN,NaN,NaN,NaN
4,False,/xJHokMbljvjADYdit5fK5VQsXEG.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,388.917,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,...,NaN,NaN,NaN,12,18,878,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50015,False,/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg,"[16, 28, 12, 35, 10751]",940551,en,Migration,After a migrating duck family alights on their...,640.652,/ldfCF9RhR40mppkzmftxapaHeTo.jpg,2023-12-06,...,NaN,NaN,NaN,16,28,12,35,10751,NaN,NaN
50016,False,/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg,"[16, 878, 28]",1209288,en,Justice League: Crisis on Infinite Earths Part...,An endless army of shadow demons bent on the d...,622.207,/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg,2024-04-22,...,NaN,NaN,NaN,16,878,28,NaN,NaN,NaN,NaN
50017,False,/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg,"[28, 53]",984324,fr,Le salaire de la peur,When an explosion at an oil well threatens hun...,497.077,/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg,2024-03-28,...,NaN,NaN,NaN,28,53,NaN,NaN,NaN,NaN,NaN
50018,False,/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg,"[10752, 28, 18]",929590,en,Civil War,"In the near future, a group of war journalists...",620.061,/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg,2024-04-10,...,NaN,NaN,NaN,10752,28,18,NaN,NaN,NaN,NaN
50019,False,/9wJO4MBzkqgUZemLTGEsgUbYyP6.jpg,"[878, 9648, 53]",720321,en,Breathe,"Air-supply is scarce in the near future, forci...",511.576,/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg,2024-04-04,...,NaN,NaN,NaN,878,9648,53,NaN,NaN,NaN,NaN

In [182]:
#como salen columnas que no quiero, las voy a borrar y me quedo con las buenas
columnas_que_borro = [f'genero{i}' for i in range(2, 10)]
df2.drop(columns=columnas_que_borro, inplace=True)

In [183]:
#ahora borro la de genero
columnas_que_borro2 = ['genero']

# Eliminar las columnas especificadas
df2.drop(columns=columnas_que_borro2, inplace=True)

In [184]:
df2

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,...,video,vote_average,vote_count,columna1,columna2,columna3,columna4,columna5,columna6,columna7
0,False,/3RWsSQlqzRjsuqSRmoyggy74UA7.jpg,"[28, 14, 35]",43074,en,Ghostbusters,"Following a ghost invasion of Manhattan, paran...",454.747,/wJmWliwXIgZOCCVOcGRBhce7xPS.jpg,2016-07-14,...,False,5.360,6186,28,14,35,NaN,NaN,NaN,NaN
1,False,/6iUNJZymJBMXXriQyFZfLAKnjO6.jpg,"[28, 12, 14]",297762,en,Wonder Woman,An Amazon princess comes to the world of Man i...,393.794,/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg,2017-05-30,...,False,7.229,19475,28,12,14,NaN,NaN,NaN,NaN
2,False,/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg,"[28, 12, 878]",284053,en,Thor: Ragnarok,Thor is imprisoned on the other side of the un...,393.367,/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg,2017-10-02,...,False,7.592,20156,28,12,878,NaN,NaN,NaN,NaN
3,False,/9X7YweCJw3q8Mcf6GadxReFEksM.jpg,"[28, 18, 878]",263115,en,Logan,"In the near future, a weary Logan cares for an...",412.050,/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg,2017-02-28,...,False,7.817,18638,28,18,878,NaN,NaN,NaN,NaN
4,False,/xJHokMbljvjADYdit5fK5VQsXEG.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,388.917,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,...,False,8.433,34210,12,18,878,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50015,False,/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg,"[16, 28, 12, 35, 10751]",940551,en,Migration,After a migrating duck family alights on their...,640.652,/ldfCF9RhR40mppkzmftxapaHeTo.jpg,2023-12-06,...,False,7.516,1255,16,28,12,35,10751,NaN,NaN
50016,False,/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg,"[16, 878, 28]",1209288,en,Justice League: Crisis on Infinite Earths Part...,An endless army of shadow demons bent on the d...,622.207,/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg,2024-04-22,...,False,6.395,43,16,878,28,NaN,NaN,NaN,NaN
50017,False,/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg,"[28, 53]",984324,fr,Le salaire de la peur,When an explosion at an oil well threatens hun...,497.077,/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg,2024-03-28,...,False,5.738,204,28,53,NaN,NaN,NaN,NaN,NaN
50018,False,/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg,"[10752, 28, 18]",929590,en,Civil War,"In the near future, a group of war journalists...",620.061,/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg,2024-04-10,...,False,7.437,500,10752,28,18,NaN,NaN,NaN,NaN
50019,False,/9wJO4MBzkqgUZemLTGEsgUbYyP6.jpg,"[878, 9648, 53]",720321,en,Breathe,"Air-supply is scarce in the near future, forci...",511.576,/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg,2024-04-04,...,False,5.000,60,878,9648,53,NaN,NaN,NaN,NaN

In [186]:
import pandas as pd

#para no ejecutarlo todo cada vez que entro de nuevo, lo paso a un CSV
df2.to_csv('df2.csv', index=False)

In [187]:
df2

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,...,video,vote_average,vote_count,columna1,columna2,columna3,columna4,columna5,columna6,columna7
0,False,/3RWsSQlqzRjsuqSRmoyggy74UA7.jpg,"[28, 14, 35]",43074,en,Ghostbusters,"Following a ghost invasion of Manhattan, paran...",454.747,/wJmWliwXIgZOCCVOcGRBhce7xPS.jpg,2016-07-14,...,False,5.360,6186,28,14,35,NaN,NaN,NaN,NaN
1,False,/6iUNJZymJBMXXriQyFZfLAKnjO6.jpg,"[28, 12, 14]",297762,en,Wonder Woman,An Amazon princess comes to the world of Man i...,393.794,/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg,2017-05-30,...,False,7.229,19475,28,12,14,NaN,NaN,NaN,NaN
2,False,/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg,"[28, 12, 878]",284053,en,Thor: Ragnarok,Thor is imprisoned on the other side of the un...,393.367,/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg,2017-10-02,...,False,7.592,20156,28,12,878,NaN,NaN,NaN,NaN
3,False,/9X7YweCJw3q8Mcf6GadxReFEksM.jpg,"[28, 18, 878]",263115,en,Logan,"In the near future, a weary Logan cares for an...",412.050,/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg,2017-02-28,...,False,7.817,18638,28,18,878,NaN,NaN,NaN,NaN
4,False,/xJHokMbljvjADYdit5fK5VQsXEG.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,388.917,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,...,False,8.433,34210,12,18,878,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50015,False,/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg,"[16, 28, 12, 35, 10751]",940551,en,Migration,After a migrating duck family alights on their...,640.652,/ldfCF9RhR40mppkzmftxapaHeTo.jpg,2023-12-06,...,False,7.516,1255,16,28,12,35,10751,NaN,NaN
50016,False,/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg,"[16, 878, 28]",1209288,en,Justice League: Crisis on Infinite Earths Part...,An endless army of shadow demons bent on the d...,622.207,/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg,2024-04-22,...,False,6.395,43,16,878,28,NaN,NaN,NaN,NaN
50017,False,/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg,"[28, 53]",984324,fr,Le salaire de la peur,When an explosion at an oil well threatens hun...,497.077,/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg,2024-03-28,...,False,5.738,204,28,53,NaN,NaN,NaN,NaN,NaN
50018,False,/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg,"[10752, 28, 18]",929590,en,Civil War,"In the near future, a group of war journalists...",620.061,/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg,2024-04-10,...,False,7.437,500,10752,28,18,NaN,NaN,NaN,NaN
50019,False,/9wJO4MBzkqgUZemLTGEsgUbYyP6.jpg,"[878, 9648, 53]",720321,en,Breathe,"Air-supply is scarce in the near future, forci...",511.576,/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg,2024-04-04,...,False,5.000,60,878,9648,53,NaN,NaN,NaN,NaN

MAPEAR GENRE_iD CON EL GÉNERO QUE CORRESPONDA

In [1]:
import requests
import json

url = "https://api.themoviedb.org/3/genre/movie/list?language=en"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.A5VdDbZhVZjV5J6iUvEWiF6WauWFOxzIK5H7Xbvc6Hc"
}

response = requests.get(url, headers=headers)
data = response.json()

# Imprimo los géneros en una lista
print("List of movie genres:")
for genre in data['genres']:
    print(f"- {genre['name']} (ID: {genre['id']})")

List of movie genres:
- Action (ID: 28)
- Adventure (ID: 12)
- Animation (ID: 16)
- Comedy (ID: 35)
- Crime (ID: 80)
- Documentary (ID: 99)
- Drama (ID: 18)
- Family (ID: 10751)
- Fantasy (ID: 14)
- History (ID: 36)
- Horror (ID: 27)
- Music (ID: 10402)
- Mystery (ID: 9648)
- Romance (ID: 10749)
- Science Fiction (ID: 878)
- TV Movie (ID: 10770)
- Thriller (ID: 53)
- War (ID: 10752)
- Western (ID: 37)

In [152]:
df.dtypes

adult                   bool
backdrop_path         object
genre_ids             object
id                     int64
original_language     object
original_title        object
overview              object
popularity           float64
poster_path           object
release_date          object
title                 object
video                   bool
vote_average         float64
vote_count             int64
columna1              object
columna2              object
columna3              object
columna4              object
columna5              object
columna6              object
columna7              object
dtype: object

In [160]:
import pandas as pd

# Suponiendo que tienes un DataFrame llamado df con las columnas columna1, columna2, ..., columna7

# Diccionario de mapeo para cada columna
mapeo_columnas = {
    'columna1': {28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy', 80: 'Crime', 99: 'Documentary', 18: 'Drama', 10751: 'Family', 14: 'Fantasy', 36: 'History', 27: 'Horror', 10402: 'Music', 9648: 'Mystery', 10749: 'Romance', 878: 'Science Fiction', 10770: 'TV Movie', 53: 'Thriller', 10752: 'War', 37: 'Western'},
    'columna2': {28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy', 80: 'Crime', 99: 'Documentary', 18: 'Drama', 10751: 'Family', 14: 'Fantasy', 36: 'History', 27: 'Horror', 10402: 'Music', 9648: 'Mystery', 10749: 'Romance', 878: 'Science Fiction', 10770: 'TV Movie', 53: 'Thriller', 10752: 'War', 37: 'Western'},
    'columna3': {28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy', 80: 'Crime', 99: 'Documentary', 18: 'Drama', 10751: 'Family', 14: 'Fantasy', 36: 'History', 27: 'Horror', 10402: 'Music', 9648: 'Mystery', 10749: 'Romance', 878: 'Science Fiction', 10770: 'TV Movie', 53: 'Thriller', 10752: 'War', 37: 'Western'}, 
    'columna4': {28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy', 80: 'Crime', 99: 'Documentary', 18: 'Drama', 10751: 'Family', 14: 'Fantasy', 36: 'History', 27: 'Horror', 10402: 'Music', 9648: 'Mystery', 10749: 'Romance', 878: 'Science Fiction', 10770: 'TV Movie', 53: 'Thriller', 10752: 'War', 37: 'Western'}, 
    'columna5': {28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy', 80: 'Crime', 99: 'Documentary', 18: 'Drama', 10751: 'Family', 14: 'Fantasy', 36: 'History', 27: 'Horror', 10402: 'Music', 9648: 'Mystery', 10749: 'Romance', 878: 'Science Fiction', 10770: 'TV Movie', 53: 'Thriller', 10752: 'War', 37: 'Western'}, 
    'columna6': {28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy', 80: 'Crime', 99: 'Documentary', 18: 'Drama', 10751: 'Family', 14: 'Fantasy', 36: 'History', 27: 'Horror', 10402: 'Music', 9648: 'Mystery', 10749: 'Romance', 878: 'Science Fiction', 10770: 'TV Movie', 53: 'Thriller', 10752: 'War', 37: 'Western'}, 
    'columna7': {28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy', 80: 'Crime', 99: 'Documentary', 18: 'Drama', 10751: 'Family', 14: 'Fantasy', 36: 'History', 27: 'Horror', 10402: 'Music', 9648: 'Mystery', 10749: 'Romance', 878: 'Science Fiction', 10770: 'TV Movie', 53: 'Thriller', 10752: 'War', 37: 'Western'}, 
}

# Convertir las columnas a tipo cadena
for columna, mapeo in mapeo_columnas.items():
    df[columna] = df[columna].map(mapeo).fillna("Desconocido")  # Si no hay mapeo, llenamos con "Desconocido"

In [161]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,...,video,vote_average,vote_count,columna1,columna2,columna3,columna4,columna5,columna6,columna7
0,False,/3RWsSQlqzRjsuqSRmoyggy74UA7.jpg,"[28, 14, 35]",43074,en,Ghostbusters,"Following a ghost invasion of Manhattan, paran...",454.747,/wJmWliwXIgZOCCVOcGRBhce7xPS.jpg,2016-07-14,...,False,5.360,6186,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido
1,False,/6iUNJZymJBMXXriQyFZfLAKnjO6.jpg,"[28, 12, 14]",297762,en,Wonder Woman,An Amazon princess comes to the world of Man i...,393.794,/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg,2017-05-30,...,False,7.229,19475,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido
2,False,/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg,"[28, 12, 878]",284053,en,Thor: Ragnarok,Thor is imprisoned on the other side of the un...,393.367,/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg,2017-10-02,...,False,7.592,20156,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido
3,False,/9X7YweCJw3q8Mcf6GadxReFEksM.jpg,"[28, 18, 878]",263115,en,Logan,"In the near future, a weary Logan cares for an...",412.050,/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg,2017-02-28,...,False,7.817,18638,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido
4,False,/xJHokMbljvjADYdit5fK5VQsXEG.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,388.917,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,...,False,8.433,34210,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50015,False,/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg,"[16, 28, 12, 35, 10751]",940551,en,Migration,After a migrating duck family alights on their...,640.652,/ldfCF9RhR40mppkzmftxapaHeTo.jpg,2023-12-06,...,False,7.516,1255,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido
50016,False,/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg,"[16, 878, 28]",1209288,en,Justice League: Crisis on Infinite Earths Part...,An endless army of shadow demons bent on the d...,622.207,/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg,2024-04-22,...,False,6.395,43,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido
50017,False,/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg,"[28, 53]",984324,fr,Le salaire de la peur,When an explosion at an oil well threatens hun...,497.077,/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg,2024-03-28,...,False,5.738,204,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido
50018,False,/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg,"[10752, 28, 18]",929590,en,Civil War,"In the near future, a group of war journalists...",620.061,/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg,2024-04-10,...,False,7.437,500,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido
50019,False,/9wJO4MBzkqgUZemLTGEsgUbYyP6.jpg,"[878, 9648, 53]",720321,en,Breathe,"Air-supply is scarce in the near future, forci...",511.576,/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg,2024-04-04,...,False,5.000,60,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido,Desconocido

In [22]:
#creo el diccionario con los generos 
genres = {genre['id']: genre['name'] for genre in data['genres']}

In [189]:
genres

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [24]:
# Mapear los números de genre_ids con los nombres de los géneros usando replace
df_años['genre_ids'] = df_años['genre_ids'].replace(genres)

In [25]:
import requests
import json

url = "https://api.themoviedb.org/3/genre/movie/list?language=en"

headers = {
    "accept": "application/json",
    "Authorization": "BearerxzIK5H7Xbvc6Hc"
}

response = requests.get(url, headers=headers)
data = response.json()
if 'genres' not in data:
    print("Error: No se encontró la clave 'genres' en la respuesta.")
    exit()

# Crear el diccionario con los géneros
genres = {genre['id']: genre['name'] for genre in data['genres']}

df_años = pd.DataFrame(data_df)

# Convertir genre_ids a tipo str y luego usar replace
df_años['genre_ids'] = df_años['genre_ids'].astype(str).replace(genres)

print(df_años)

NameError: name 'data_df' is not defined

In [ ]:
import requests
import json
import pandas as pd


# Verificar si 'genres' está en la respuesta
if 'genres' not in genres:
    print("Error: No se encontró la clave 'genres' en la respuesta.")
    exit()

# Crear el diccionario con los géneros
genres = {genre['id']: genre['name'] for genre in data['genres']}

# Convertir genre_ids a tipo str y luego usar replace
df_años['genre_ids'] = df_años['genre_ids'].astype(str).replace(genres)

print(df_años)

NameError: name 'genres' is not defined

In [ ]:
df_años.tail()

   movie_id genre_ids
0         1        28
1         2        35
2         3        18

In [ ]:
# Check if column is numerical
if pd.api.types.is_numeric_dtype(df_años['genre_ids']):
  # Replace values and potentially drop the 'genre_ids' column
  df_años['genre_names'] = df_años['genre_ids'].replace(genres, method='mapping')
  if not pd.api.types.is_string_dtype(df_años['genre_names']):
    df_años.drop('genre_ids', axis=1, inplace=True)

print(df_años)

       adult                     backdrop_path                    genre_ids  \
0      False  /kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg                [28, 12, 878]
1      False  /xJHokMbljvjADYdit5fK5VQsXEG.jpg                [12, 18, 878]
2      False  /zCjZfevPFBbOh2SAx2syIBHSqEI.jpg                [28, 18, 878]
3      False  /mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg                [12, 28, 878]
4      False  /mVr0UiqyltcfqxbAUcLl9zWL8ah.jpg                    [878, 18]
...      ...                               ...                          ...
49995  False                              None                 [Documental]
49996  False  /7SNMu0eBx6uFciONIlUVjFniPkl.jpg  [Fantasía, Aventura, Drama]
49997  False  /aYgKXzcngL7TKs6p9NhjYfYJK1G.jpg                      [Drama]
49998  False  /gObMmG8I701bhO2xhV751LirlKv.jpg                    [Comedia]
49999  False  /8mGwBZm61PipyMbGIYFkjaNPbl9.jpg                      [Drama]

            id original_language  \
0       284053                en
1       157336                en
2       124905                en
3       299536                en
4       335984                en
...        ...               ...
49995  1002181                en
49996   942921                en
49997   913276                ru
49998   883016                pt
49999  1161242                de

                                        original_title  \
0                                       Thor: Ragnarok
1                                         Interstellar
2                                             Godzilla
3                               Avengers: Infinity War
4                                    Blade Runner 2049
...                                                ...
49995  American Badass: A Michael Madsen Retrospective
49996                               Call of the Unseen
49997                                             Ника
49998                                    O Pai da Rita
49999                                             Vika

                                                overview  popularity  \
0      Thor is imprisoned on the other side of the un...     249.493
1      The adventures of a group of explorers who mak...     192.574
2      Ford Brody, a Navy bomb expert, has just reuni...     189.689
3      As the Avengers and their allies have continue...     184.397
4      Thirty years after the events of the first fil...     168.581
...                                                  ...         ...
49995  An intimate, soul-baring new documentary cover...       1.619
49996  A young artist loses her confidence. An old ar...       1.619
49997  The movie is based on the real story of Nika T...       1.619
49998  Roque and Pudim, composers from the old school...       1.619
49999  The craftswoman Vika loves her secluded life. ...       1.618

                            poster_path release_date  \
0      /rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg   2017-10-02
1      /gEU2QniE6E77NI6lCU6MxlNBvIx.jpg   2014-11-05
2      /zokD6uxR2iWfYM3Y84yGJvnNTK7.jpg   2014-05-14
3      /7WsyChQLEftFiDOVTGkv3hFpyyt.jpg   2018-04-25
4      /gajva2L0rPYkEWjzgFlBXCAVBE5.jpg   2017-10-04
...                                 ...          ...
49995  /kIXtt9GejWPNstOuqKEgEVEdA6b.jpg   2022-08-15
49996  /peuL3gyrAsLNiZLSr6SE0NJeBNv.jpg   2022-11-02
49997  /AsRDGCYuQDJPa3lv4FrymSfTeYe.jpg   2022-05-19
49998  /t1Xs4xqE7pk3A6cbq5ohJagoNt2.jpg   2022-05-19
49999  /qfNRHH13pSj6o1WauRIlXR7HzTq.jpg   2022-10-27

                                                 title  video  vote_average  \
0                                       Thor: Ragnarok  False         7.595
1                                         Interstellar  False         8.433
2                                             Godzilla  False         6.320
3                               Avengers: Infinity War  False         8.248
4                                    Blade Runner 2049  False         7.600
...                                                ...    ...           ...
49995  American Badass: A Michael Madsen Retrospective  False         2.000
49996                             The Resourceful Girl  False         6.200
49997                                             Nika  False         6.000
49998                                    O Pai da Rita  False         5.400
49999                                             Vika  False         7.000

       vote_count                  genre_names
0           20093                [28, 12, 878]
1           34063                [12, 18, 878]
2            8758                [28, 18, 878]
3           28746                [12, 28, 878]
4           12982                    [878, 18]
...           ...                          ...
49995           1                 [Documental]
49996           5  [Fantasía, Aventura, Drama]
49997           5                      [Drama]
49998           4                    [Comedia]
49999           1                      [Drama]

[50000 rows x 15 columns]

In [ ]:
import pandas as pd

# Save DataFrame to CSV
df.to_csv('movies_with_genre_names.csv', index=False)

In [ ]:
df_final = pd.read_csv('movies_with_genre_names.csv')

In [ ]:
df_final.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg,"[878, 28, 14, 12]",601796,ko,외계+인 1부,Gurus in the late Goryeo dynasty try to obtain...,1805.501,/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg,2022-07-20,Alienoid,False,7.091,257
1,False,/9c0lHTXRqDBxeOToVzRu0GArSne.jpg,"[878, 28]",935271,en,After the Pandemic,Set in a post-apocalyptic world where a global...,906.812,/p1LbrdJ53dGfEhRopG71akfzOVu.jpg,2022-03-01,After the Pandemic,False,5.061,41
2,False,/2c2Osibm2Q1eEJCW8jc98GQhGdc.jpg,"[12, 28]",893334,en,The Adventures of Maid Marian,Everyone knows the stories of Robin Hood and M...,688.768,/oPXzCV01ysDmnmpJOkiVqaZQ5QR.jpg,2022-05-09,The Adventures of Maid Marian,False,4.900,11
3,False,/rKmp0vm6PNaFA0g1bzM70eyWJ6I.jpg,[28],873972,en,Hunters,As John T. Wrecker continues his task of prote...,559.284,/3UKlVa1CBeQkRksHV5OfFTO52qd.jpg,2021-09-13,Hunters,False,6.533,15
4,False,/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg,"[878, 12]",438631,en,Dune,"Paul Atreides, a brilliant and gifted young ma...",508.041,/d5NXSklXo0qyIYkgV94XAgMIckC.jpg,2021-09-15,Dune,False,7.790,11190